'''
Created on Mar 8, 2013

@author: Daniel
'''
NUM_POPULATIONS = 2
NUM_INDIVIDUALS = 10
PRUNING_NUM = 5
MUTATION_PROBABILITY = 1
STRUCTURE_MUTATION_PROBABILITY = 0.1
NUM_GENE_MUTATIONS = 1
#NUM_GENERATIONS = 50
NUM_GAME_REPETITIONS = 50

NUM_INITIAL_STATES = 8
DEFAULT_MEMORY = 1
ACTION_PROB_STEP_NUM = 16
ACTION_PROB_LEN = len(bin(ACTION_PROB_STEP_NUM)[2:])